import { useState } from 'react';
import axios from 'axios';

function App() {
  const [input, setInput] = useState('');
  const [testCases, setTestCases] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isGherkin, setIsGherkin] = useState(true);

  const handleGenerate = async () => {
    if (!input.trim()) return;
    setIsLoading(true);
    try {
      const response = await axios.post(
        'https://test-case-backend-phani.vercel.app/generate-test-cases',
        {
          input,
          format: isGherkin ? 'gherkin' : 'normal',
        }
      );
      setTestCases(response.data.testCases);
    } catch (error) {
      console.error('Error generating test cases:', error);
      setTestCases('❌ Failed to generate test cases. Please try again later.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleToggle = () => setIsGherkin(!isGherkin);

  return (
    <div className="min-h-screen bg-gray-900 text-white px-4 py-8">
      <div className="max-w-4xl mx-auto border border-dashed border-orange-400 p-6 rounded-lg">
        <div className="flex items-center gap-3 mb-6">
          <img src="/bk-favicon.png" alt="BK" className="h-8 w-8" />
          <h1 className="text-3xl font-bold">Test Case Generator</h1>
        </div>

        <div className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <input
              type="checkbox"
              checked={isGherkin}
              onChange={handleToggle}
              className="accent-orange-500"
            />
            <label className="text-sm">Gherkin Format</label>
          </div>

          <textarea
            className="p-3 w-full h-36 rounded bg-gray-800 text-white border border-gray-600 placeholder-gray-400 resize-none"
            placeholder="Paste acceptance criteria or feature description..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
          />

          <button
            className="bg-amber-500 hover:bg-amber-600 text-black font-semibold py-2 px-4 rounded w-fit"
            onClick={handleGenerate}
            disabled={isLoading}
          >
            {isLoading ? 'Generating...' : `Generate ${isGherkin ? 'Gherkin' : 'Normal'} Test Cases`}
          </button>
        </div>

        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-2">Generated Test Cases:</h2>
          <p className="text-sm text-yellow-300 mb-3">
            ⚠️ These test cases are generated by AI and may still contain errors. Please review with your human brain 🧠.
          </p>
          <pre className="whitespace-pre-wrap text-sm text-gray-200">
            {testCases || 'No test cases generated yet.'}
          </pre>
        </div>
      </div>
    </div>
  );
}

export default App;