import { useState } from 'react';
import './App.css';
import logo from './assets/burger-king-logo.png';

function App() {
  const [input, setInput] = useState('');
  const [testCases, setTestCases] = useState([]);
  const [gherkinFormat, setGherkinFormat] = useState(true);
  const [darkMode, setDarkMode] = useState(false);

  const generateTestCases = async () => {
    const res = await fetch('https://test-case-backend-ten.vercel.app/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ input, gherkinFormat }),
    });
    const data = await res.json();
    setTestCases(data.testCases || []);
  };

  const exportExcel = async (data) => {
    const XLSX = await import('xlsx');
    const worksheet = XLSX.utils.json_to_sheet(data.map((t, i) => ({ ID: i + 1, TestCase: t })));
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'TestCases');
    XLSX.writeFile(workbook, 'Generated_Test_Cases.xlsx');
  };

  return (
    <div className={`min-h-screen px-4 py-8 ${darkMode ? 'bg-gray-900 text-white' : 'bg-white text-black'}`}>
      <div className="max-w-3xl mx-auto space-y-6">
        <div className="flex justify-between items-center">
          <img src={logo} alt="BK Logo" className="w-40 sm:w-56" />
          <label className="flex items-center space-x-2">
            <input type="checkbox" checked={darkMode} onChange={() => setDarkMode(!darkMode)} />
            <span>Dark Mode</span>
          </label>
        </div>

        <h1 className="text-2xl sm:text-3xl font-bold flex items-center">
          🧪 Test Case Generator
        </h1>

        <div className="space-y-4">
          <label className="flex items-center space-x-2">
            <input
              type="checkbox"
              checked={gherkinFormat}
              onChange={() => setGherkinFormat(!gherkinFormat)}
            />
            <span>Gherkin Format</span>
          </label>

          <textarea
            rows="4"
            placeholder="Paste acceptance criteria or feature"
            className="w-full p-2 border rounded"
            value={input}
            onChange={(e) => setInput(e.target.value)}
          />

          <button
            onClick={generateTestCases}
            className="bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 rounded"
          >
            Generate Gherkin Test Cases
          </button>
        </div>

        <div className="mt-6">
          <h2 className="text-xl font-semibold">Generated Test Cases:</h2>
          <p className="text-yellow-600 mt-2">
            ⚠️ These test cases are generated by AI and may still contain errors. Please review with your human brain 🧠.
          </p>
          <ul className="list-disc ml-6 mt-4 space-y-1">
            {testCases.map((tc, i) => (
              <li key={i}>{tc}</li>
            ))}
          </ul>

          {testCases.length > 0 && (
            <button
              onClick={() => exportExcel(testCases)}
              className="bg-green-600 hover:bg-green-700 text-white py-2 px-4 rounded shadow-md mt-4"
            >
              📤 Export to Excel
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

export default App;